---

- name: install nginx
  yum:
    name: "{{ item }}"
  loop:
    - epel-release
    - nginx

- name: enable nginx
  systemd:
    name: nginx
    enabled: yes

- name: configure main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify: reload nginx

- name: configure servers
  template:
    src: server.conf.j2
    dest: /etc/nginx/conf.d/server.conf
    mode: 0644
    owner: root
    group: root
  notify: reload nginx

- name: create directory for static
  file:
    path: "{{ nginx_static_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: deploy static
  copy:
    src: index.html
    dest: "{{ nginx_static_path }}/"
    mode: 0644
    owner: root
    group: root
