name: deploy

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1

      - uses: dschep/install-pipenv-action@v1

      - name: Run 11-docker
        run: 11-docker/bin/run.sh